TASK: ImageCaptioningTask

DATASET:
  FEATURE_DATASET:
    TYPE: OpenViLCImageCaptioningFeatureDataset
    BATCH_SIZE: 64
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: data\open_vilc\features\vinvl_vinvl
      SCENE_TEXT: null
      IMAGE: data\open_vilc\images
  VOCAB:
    TYPE: OpenViLCCaptioningVocab
    TOKENIZER: null
    MIN_FREQ: 1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    IMG_TOKEN: <img>
    FEAT_TOKEN: <feat>
    BOX_TOKEN: <box>
    PAD_TOKEN: <pad>
    CAPTION_TOKEN: <caption>
    MAX_CAPTION_LENGTH: 0
    JSON_PATH:
      TRAIN: data\open_vilc\uit-openviic-train.json
      DEV: data\open_vilc\uit-openviic-dev.json
      TEST: data\open_vilc\uit-openviic-test.json
  JSON_PATH:
    TRAIN: data\open_vilc\uit-openviic-train.json
    DEV: data\open_vilc\uit-openviic-dev.json
    TEST: data\open_vilc\uit-openviic-test.json

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 0.002
  WARMUP: 10000
  SCORE: CIDEr
  GET_SCORES: True
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 3
  PATIENCE: 5
  VERBOSE_SCORES:
    - CIDEr
    - BLEU
    - ROUGE
    - Accuracy
    - F1
    - Precision
    - Recall

MODEL:
  ARCHITECTURE: MCANCaptioning
  NAME: mcan_openvilc_region_x152++_faster_rcnn_captioning
  DEVICE: cuda
  D_MODEL: 512
  VISION_EMBEDDING:
    ARCHITECTURE: FeatureEmbedding
    D_FEATURE: 2048
    D_MODEL: 512
    DROPOUT: 0.1
  TEXT_EMBEDDING:
    ARCHITECTURE: LSTMTextEmbedding
    D_MODEL: 512
    D_EMBEDDING: 300
    DROPOUT: 0.1
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
  SELF_ENCODER:
    ARCHITECTURE: Encoder
    D_MODEL: 512
    LAYERS: 3
    SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: 0.1
  GUIDED_ENCODER:
    ARCHITECTURE: GuidedAttentionEncoder
    D_MODEL: 512
    LAYERS: 3
    SELF_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: 0.1
    GUIDED_ATTENTION:
      ARCHITECTURE: ScaledDotProductAttention
      HEAD: 8
      D_MODEL: 512
      D_KEY: 64
      D_VALUE: 64
      D_FF: 2048
      D_FEATURE: 2048
      USE_AOA: False
      CAN_BE_STATEFUL: False
      DROPOUT: 0.1
  VISION_ATTR_REDUCE:
    D_MODEL: 512
    DROPOUT: 0.1
  TEXT_ATTR_REDUCE:
    D_MODEL: 512
    DROPOUT: 0.1
  DECODER:
    ARCHITECTURE: Decoder
    D_MODEL: 512
    LAYERS: 3
    ATTENTION:
      SELF_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: True
        DROPOUT: .1
      ENC_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: False
        DROPOUT: .1
    TEXT_EMBEDDING:
      ARCHITECTURE: UsualEmbedding
      D_MODEL: 512
      D_EMBEDDING: 300
      WORD_EMBEDDING: null
      WORD_EMBEDDING_CACHE: null
      DROPOUT: 0.1
  DROPOUT: 0.1