TASK: VlspEvjVqaTask

DATASET:
  FEATURE_DATASET:
    TYPE: MultilingualImageQuestionDataset
    BATCH_SIZE: 60
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: null
      SCENE_TEXT: null
      IMAGE:  data/vivqa_v2/images
    SCENE_TEXT_THRESHOLD: 0.3
  DICT_DATASET:
    TYPE: MultilingualImageQuestionDictionaryDataset
    BATCH_SIZE: 60
    WORKERS: 0
    FEATURE_PATH:
      FEATURES: null
      SCENE_TEXT: null
      IMAGE:  data/vivqa_v2/images
    SCENE_TEXT_THRESHOLD: 0.3
  MIN_FREQ: 1
  VOCAB:
    TYPE: VlspEvjVqaVocab
    TOKENIZER: null
    WORD_EMBEDDING: null
    WORD_EMBEDDING_CACHE: null
    BOS_TOKEN: <bos>
    EOS_TOKEN: <eos>
    PAD_TOKEN: <pad>
    UNK_TOKEN: <unk>
    USE_MAPPING: False
    JSON_PATH:
      TRAIN: data/vivqa_v2/vivqa_v2_train.json
      DEV: data/vivqa_v2/vivqa_v2_dev.json
      TEST: data/vivqa_v2/vivqa_v2_test.json
  JSON_PATH:
    TRAIN: data/vivqa_v2/vivqa_v2_train.json
    DEV: data/vivqa_v2/vivqa_v2_dev.json
    PUBLIC_TEST: data/vivqa_v2/vivqa_v2_test.json
    PRIVATE_TEST: data/vivqa_v2/vivqa_v2_test.json

TRAINING:
  CHECKPOINT_PATH: saved_models
  LEARNING_RATE: 0.001
  RL_LEARNING_RATE: 0.000005
  WARMUP: 10000
  SCORE: CIDEr
  TRAINING_BEAM_SIZE: 5
  EVALUATING_BEAM_SIZE: 3
  PATIENCE: 5
  VERBOSE_SCORES:
    - CIDEr
    - BLEU
    - ROUGE
    - Accuracy
    - F1
    - Precision
    - Recall


MODEL:
  ARCHITECTURE: ViTmT5
  NAME: vit_mt5
  DEVICE: cuda
  VISION_EMBEDDING:
    ARCHITECTURE: ViTEmbedding
    PRETRAINED_NAME: google/vit-base-patch16-224-in21k
    DEVICE: cuda
    D_PRETRAINED_FEATURE: 768
    D_MODEL: 512
    DROPOUT: .1
  TEXT_EMBEDDING:
    ARCHITECTURE: T5Embedding
    PRETRAINED_NAME: google/mt5-small
    DEVICE: cuda
    D_PRETRAINED_FEATURE: 512
    D_MODEL: 512
    DROPOUT: .1
  MULTIMODAL_FUSION:
    TYPE: IterativeMultimodalFusion
    D_MODEL: 512
    DROPOUT: 0.1
    N_LAYERS: 3
    N_HEADS: 8
    D_FF: 2048
    USE_AOA: False
    CAN_BE_STATEFUL: True
    DROPOUT: 0.1
  D_MODEL: 512
  DROPOUT: .1
  DECODER:
    ARCHITECTURE: Decoder
    D_MODEL: 512
    LAYERS: 3
    ATTENTION:
      SELF_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: True
        DROPOUT: .1
      ENC_ATTENTION:
        ARCHITECTURE: ScaledDotProductAttention
        HEAD: 8
        D_MODEL: 512
        D_KEY: 64
        D_VALUE: 64
        D_FF: 2048
        D_FEATURE: 2048
        USE_AOA: False
        CAN_BE_STATEFUL: False
        DROPOUT: .1
    TEXT_EMBEDDING:
      ARCHITECTURE: UsualEmbedding
      D_MODEL: 512
      D_EMBEDDING: 300
      WORD_EMBEDDING: null
      WORD_EMBEDDING_CACHE: null
      DROPOUT: 0.1